services:
  frontend:
    build: .
    container_name: hackme-frontend
    ports:
      - '3000:3000'
    restart: unless-stopped
    env_file:
      - .env
      - .env.docker 

  extra_hosts:
      - "host.docker.internal:host-gateway"
    
